### ISSUE TITLE
GramFuzzer import error

### ISSUE THREAD

**Issue by s4bu** [dzonerzy/PyJFAPI#5]
Hi I am getting following error:

python test.py 
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    from test import test_pjf_factory
  File "/root/fuzzer/PyJFuzz/test/test_pjf_factory.py", line 24, in <module>
    from pyjfuzz.core.pjf_configuration import PJFConfiguration
  File "/root/fuzzer/PyJFuzz/pyjfuzz/core/pjf_configuration.py", line 32, in <module>
    from .pjf_grammar import generate_json
  File "/root/fuzzer/PyJFuzz/pyjfuzz/core/pjf_grammar.py", line 25, in <module>
    from gramfuzz import GramFuzzer
ImportError: cannot import name GramFuzzer

**Comment by s4bu** [comment]
I fixed it by manually installing the latest copy of gramfuzz ==1.2.1
